from backend.app.admin.model.crawl_task import CrawlTask as CrawlTask
from backend.app.admin.model.crawl_task import CrawlTaskLog as CrawlTaskLog
from backend.app.admin.model.crawl_elec import CrawlElecRecord as CrawlElecRecord
from backend.app.admin.model.data_flow import DataFlow as DataFlow
from backend.app.admin.model.data_flow import DataFlowRun as DataFlowRun
from backend.app.admin.model.data_quality import QualityCheck as QualityCheck
from backend.app.admin.model.data_quality import QualityRule as QualityRule
from backend.app.admin.model.data_rule import DataRule as DataRule
from backend.app.admin.model.data_storage import DataLayer as DataLayer
from backend.app.admin.model.data_storage import Dataset as Dataset
from backend.app.admin.model.data_scope import DataScope as DataScope
from backend.app.admin.model.datasource import Datasource as Datasource
from backend.app.admin.model.dept import Dept as Dept
from backend.app.admin.model.login_log import LoginLog as LoginLog
from backend.app.admin.model.m2m import data_scope_rule as data_scope_rule
from backend.app.admin.model.m2m import role_data_scope as role_data_scope
from backend.app.admin.model.m2m import role_menu as role_menu
from backend.app.admin.model.m2m import user_role as user_role
from backend.app.admin.model.menu import Menu as Menu
from backend.app.admin.model.opera_log import OperaLog as OperaLog
from backend.app.admin.model.query import QueryHistory as QueryHistory
from backend.app.admin.model.query import SavedQuery as SavedQuery
from backend.app.admin.model.report import Report as Report
from backend.app.admin.model.report import ReportWidget as ReportWidget
from backend.app.admin.model.role import Role as Role
from backend.app.admin.model.server import Server as Server
from backend.app.admin.model.user import User as User
from backend.app.admin.model.user_password_history import UserPasswordHistory as UserPasswordHistory
from backend.app.admin.model.alert import AlertHistory as AlertHistory
from backend.app.admin.model.alert import AlertRule as AlertRule
from backend.app.admin.model.audit_log import AuditLog as AuditLog
from backend.app.admin.model.data_permission import DataMaskingRule as DataMaskingRule
from backend.app.admin.model.data_permission import ResourcePermission as ResourcePermission
from backend.app.admin.model.worker import WorkerNode as WorkerNode

# AI 助手模型 (在 sys_ 前缀表中存储)
from backend.app.assistant.model import AiConfig as AiConfig
from backend.app.assistant.model import AiChatHistory as AiChatHistory

# 移动端版本管理模型
from backend.app.mobile.model import AppVersion as AppVersion
